definitions:
  domain.ConnectionDetails:
    properties:
      dbname:
        type: string
      host:
        type: string
      password:
        type: string
      port:
        type: integer
      user:
        type: string
    type: object
  domain.Schema:
    properties:
      id:
        type: string
      name:
        type: string
      summary_id:
        type: string
      synced_at:
        type: string
      tables:
        items:
          $ref: '#/definitions/domain.Table'
        type: array
    type: object
  domain.Summary:
    properties:
      id:
        type: string
      schemas:
        items:
          $ref: '#/definitions/domain.Schema'
        type: array
      source_info:
        $ref: '#/definitions/domain.ConnectionDetails'
      synced_at:
        type: string
    type: object
  domain.Table:
    properties:
      id:
        type: string
      name:
        type: string
      row_count:
        type: integer
      schema_id:
        type: string
      size_mb:
        type: number
    type: object
info:
  contact: {}
paths:
  /summary/summaries:
    get:
      description: Retrieves paginated summaries
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Summary'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all summaries
      tags:
      - summary
  /summary/summaries/{id}:
    get:
      description: Retrieves full summary by ID
      parameters:
      - description: Summary ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Summary'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get summary by ID
      tags:
      - summary
  /summary/sync:
    post:
      consumes:
      - application/json
      description: Connects to remote PostgreSQL via external API and saves summary
      parameters:
      - description: Remote DB connection
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/domain.ConnectionDetails'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Summary'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Sync a new database summary
      tags:
      - summary
swagger: "2.0"
